In [1]:
import sys
import numpy as np
import glob
import matplotlib.pyplot as plt

In [2]:
## labels
#1:
tb_1 = 36393
ts_1 = 3543
print tb_1
print ts_1
print "1: %d" %(tb_1 + ts_1)
labels_1 = np.vstack((np.zeros((tb_1, 1), dtype='int64'), np.ones((ts_1, 1), dtype='int64')))
print labels_1.shape
#2:
tb_2 = 64446
ts_2 = 2010
print tb_2
print ts_2
print "2: %d" %(tb_2 + ts_2)
labels_2 = np.vstack((np.zeros((tb_2, 1), dtype='int64'), np.ones((ts_2, 1), dtype='int64')))
print labels_2.shape
#3:
tb_3 = 47182
ts_3 = 1762
print tb_3
print ts_3
print "3: %d" %(tb_3 + ts_3)
labels_3 = np.vstack((np.zeros((tb_3, 1), dtype='int64'), np.ones((ts_3, 1), dtype='int64')))
print labels_3.shape
#4:
tb_4 = 68887
ts_4 = 2738
print tb_4
print ts_4
print "4: %d" %(tb_4 + ts_4)
labels_4 = np.vstack((np.zeros((tb_4, 1), dtype='int64'), np.ones((ts_4, 1), dtype='int64')))
print labels_4.shape
#5:
tb_5 = 53119
ts_5 = 842
print tb_5
print ts_5
print "5: %d" %(tb_5 + ts_5)
labels_5 = np.vstack((np.zeros((tb_5, 1), dtype='int64'), np.ones((ts_5, 1), dtype='int64')))
print labels_5.shape
#6:
tb_6 = 59210
ts_6 = 1746
print tb_6
print ts_6
print "6: %d" %(tb_6 + ts_6)
labels_6 = np.vstack((np.zeros((tb_6, 1), dtype='int64'), np.ones((ts_6, 1), dtype='int64')))
print labels_6.shape
#7:
tb_7 = 93628
ts_7 = 2810
print tb_7
print ts_7
print "7: %d" %(tb_7 + ts_7)
labels_7 = np.vstack((np.zeros((tb_7, 1), dtype='int64'), np.ones((ts_7, 1), dtype='int64')))
print labels_7.shape
#8:
tb_8 = 83403
ts_8 = 2865
print tb_8
print ts_8
print "8: %d" %(tb_8 + ts_8)
labels_8 = np.vstack((np.zeros((tb_8, 1), dtype='int64'), np.ones((ts_8, 1), dtype='int64')))
print labels_8.shape

36393
3543
1: 39936
(39936, 1)
64446
2010
2: 66456
(66456, 1)
47182
1762
3: 48944
(48944, 1)
68887
2738
4: 71625
(71625, 1)
53119
842
5: 53961
(53961, 1)
59210
1746
6: 60956
(60956, 1)
93628
2810
7: 96438
(96438, 1)
83403
2865
8: 86268
(86268, 1)


In [3]:
# getting data
CVsplit="5"
p_path_all = "predictions/" + CVsplit + "/*"
print(p_path_all)
predictions_path_all = glob.glob(p_path_all)
print(len(predictions_path_all))
preds = []
for predictions_path in predictions_path_all:
    print(predictions_path)
    preds.append(np.load(predictions_path))

for pred in preds:
    print pred.shape
avrg_preds = (preds[0]+preds[1]+preds[2])/len(preds)
print avrg_preds[20000:20010]
print(type(avrg_preds))
plt.plot(avrg_preds[:], 'ro', markersize=3)
plt.show()

predictions/5/*
3
predictions/5/predictions_LSTM-5-20160211-001225-10.npy
predictions/5/predictions_LSTM-5-20160211-001225-13.npy
predictions/5/predictions_LSTM-5-20160211-001225-11.npy
(53961, 1)
(53961, 1)
(53961, 1)
[[ 0.00365882]
 [ 0.00767244]
 [ 0.00127533]
 [ 0.00365882]
 [ 0.02946481]
 [ 0.00767244]
 [ 0.00924406]
 [ 0.00026174]
 [ 0.00365882]
 [ 0.02946481]]
<type 'numpy.ndarray'>


In [13]:
## Confusion matrix
def get_prediction_hot(p, cutoff=0.5):
    y = (p>cutoff).astype('int')
    return y
#print get_prediction_hot(avrg_preds).dtype
#print labels_5.dtype
from sklearn.metrics import confusion_matrix
cm_25 = confusion_matrix(labels_5.tolist(), get_prediction_hot(avrg_preds, cutoff=0.001).tolist())
cm_50 = confusion_matrix(labels_5.tolist(), get_prediction_hot(avrg_preds, cutoff=0.999).tolist())
cm_75 = confusion_matrix(labels_5.tolist(), get_prediction_hot(avrg_preds, cutoff=0.75).tolist())
print cm_25 
print cm_50
print cm_75

[[42912 10207]
 [    0   842]]
[[53119     0]
 [  560   282]]
[[53119     0]
 [   28   814]]


In [12]:
def plot_confusion_matrix(cm, title='Confusion matrix 0.50 cutoff, normalized', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
#    tick_marks = np.arange(len(iris.target_names))
#    plt.xticks(tick_marks, iris.target_names, rotation=45)
#    plt.yticks(tick_marks, iris.target_names)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

cm_50_norm = cm_50.astype('float64') / cm_50.sum().astype('float64')
#plt.figure()
plot_confusion_matrix(cm_50)
plt.show()